# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lesson9-homework-1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SnapKit', '~> 5.6.0'
  
  # Pods for lesson9-homework-1

end
